server:
  port: 8457
logging:
  file: /java/C2S_LOGS/pcm/pcm.log
info:
  component: Patient Consent Management Service
ribbon:
  ReadTimeout: 50000
hystrix.command.default.execution.timeout.enabled: false
spring:
  datasource:
    # configure url, username and password per environment
    url: jdbc:mysql://localhost:3306/pcm?autoReconnect=true
    username: root
    password: admin
c2s:
  pcm:
    supported-provider-systems:
      - "http://hl7.org/fhir/sid/us-npi"
    consent:
      attestation-term-id-when-patient-signs: 1
      attestation-term-id-when-provider-signs: 2

      revocation-term-id-when-patient-revokes: 1
      revocation-term-id-when-provider-revokes: 1
      publish:
        enabled: false
        # configure fhir server base url
        serverUrl: http://bhitsdevhie01/hapi-fhir-jpaserver/baseStu3
        clientSocketTimeoutInMs: 768000
    fhir:
      ssn:
        system: http://hl7.org/fhir/sid/us-ssn
        oid: urn:oid:2.16.840.1.113883.4.1
        label: SSN
      npi:
        system: http://hl7.org/fhir/sid/us-npi
        oid: urn:oid:2.16.840.1.113883.4.6
        label: PRN
      pou:
        system: http://hl7.org/fhir/v3/ActReason
        oid: urn:oid:2.16.840.1.113883.1.11.20448
        label: PurposeOfUse
      mrn:
        system: https://bhits.github.io/consent2share
        oid: urn:oid:1.3.6.1.4.1.21367.13.20.200
        label: MRN
      patientReference: true
    activity:
      sqls:
        - file-path: activity/consent-activity.sql
      pagination:
        default-size: 10
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /pcm
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://${C2S_DB_HOST:pcm-db.c2s.com}:${C2S_DB_PORT:3306}/pcm?autoReconnect=true
c2s:
  pcm:
    consent:
      publish:
        # configure fhir server base url
        serverUrl: http://hapi-fhir.c2s.com:8080/hapi-fhir-jpaserver/baseStu3